### ISSUE TITLE
Can't activate Tasks

### ISSUE THREAD

**Issue by Tramour** [libasys/ownCloud-8.1-Task-App#1]
Installed latest version in Apps folder. Folder named tasks.
I get an error while trying to activate the app (see picture).
![screenshot 2015-06-23 22 45 13](https://cloud.githubusercontent.com/assets/13016794/8316888/10d36a3e-19fa-11e5-851e-0fe9199bba90.png)

"No app name specified"

**Comment by libasys** [comment]
Please add more info to your Bug Reports! What says the logs on the Admin settings Page! What is your Environment ? Apache MySQL etc! What says the js error Log of your Browser? Thanks!

**Comment by Tramour** [comment]
Admin log is empty. No js errors. MySQL 6.5.23. PHP 5.5.22. Hosted by all inkl. 
I checked your info.xml:

<id>aufgaben</id>
<name>Tasks Advanced</name>
<licence>AGPL</licence>
<author>Döll Sebastian</author>
<shipped>false</shipped>
<description>The tasks apps comes with a lot of improvements to have more options to work with tasks</description>
<namespace>Aufgaben</namespace>
<website>https://github.com/libasys/ownCloud-8.1-Task-App</website>
<version>1.0.1</version>
<category>productivity</category>

Is 'Aufgaben' in XML correct? I named the directory tasks.

**Comment by libasys** [comment]
no, the name of the folder must be "aufgaben"! you have to rename the folder to aufgaben! than the app works!

**Comment by Tramour** [comment]
Okay. Now it works. 
Maybe you can give a hint in the readme that the app's foldername must be 'aufgaben'.

**Comment by libasys** [comment]
I think this should be clear this foldername is internal and should be unique! Another task app has a folder named task, so i have to choose another name for my task app ;) !
